version: '3'


services:
  # HomeAssistant
  homeassistant:
    image: homeassistant/home-assistant
    container_name: HomeAssistant
    volumes:
      - ${SmartHomeDir}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    depends_on:
      - Mosquitto
    restart: unless-stopped

  # Influxdb
  influxdb:
    image: influxdb:2.1
    container_name: Influxdb
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - ${SmartHomeDir}/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=${username}
      - INFLUXDB_ADMIN_PASSWORD=${password}
      - INFLUXDB_DB="speedtest"
      - INFLUXDB_DB="homeassistant"
    restart: unless-stopped

  # Grafana
  grafana:
    image: grafana/grafana:5.4.3
    container_name: Grafana
    ports:
      - 3000:3000
    volumes:
      - ${SmartHomeDir}/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped
    
  # Mosquitto
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: Mosquitto
    ports:
      - 1883:1883
    volumes:
      - ${SmartHomeDir}/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${SmartHomeDir}/mosquitto/users:/mosquitto/config/users
      - ${SmartHomeDir}/mosquitto/data:/mosquitto/data
      - ${SmartHomeDir}/mosquitto/log:/mosquitto/log
    environment:
      - MQTT_USERNAME=${username}
      - MQTT_PASSWORD=${password}
    restart: unless-stopped

  # Speedtest
  speedtest:
    image: robinmanuelthiel/speedtest:latest
    container_name: Speedtest
    environment:
      - LOOP=true
      - LOOP_DELAY=1800
      - DB_SAVE=true
      - DB_HOST=http://influxdb:8086
      - DB_NAME=speedtest
      - DB_USERNAME=${username}
      - DB_PASSWORD=${password}
    privileged: true # Needed for 'sleep' in the loop
    depends_on:
      - influxdb
    restart: unless-stopped

  # Zigbee2mqtt
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    ports:
      # Frontend port
      - 8080:8080
    volumes:
      - ${SmartHomeDir}/Zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Amsterdam
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyAMA0:/dev/ttyACM0
    depends_on:
      - Mosquitto
    restart: unless-stopped
  
  # Node-Red
  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - 1880:1880
    volumes:
      - ${SmartHomeDir}/nodered:/data
    environment:
      - NODE_RED_USERNAME=admin
      - NODE_RED_PASSWORD=password
    depends_on:
      - mosquitto
      - homeassistant
      - influxdb
    restart: unless-stopped

  # mqtt-bridge
  mqttbridge:
    build: ${SmartHomeDir}/mqtt2influxdb_bridge
    container_name: mqttbridge
    depends_on:
      - mosquitto
      - influxdb
    restart: unless-stopped

  # Portainer
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${SmartHomeDir}/portainer:/data
    depends_on:
      - Mosquitto
    environment:
      - PORT=9000
      - HOST=
    restart: unless-stopped

